// <auto-generated />
using Conway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Conway.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211027083534_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Conway.Core.Model.BAT_Cigarette", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Eancode")
                        .HasColumnType("bigint");

                    b.Property<string>("Fabrikant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Nielsen1")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen2")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen3")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen4")
                        .HasColumnType("float");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ref")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BAT_Cigarettes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "red",
                            Eancode = 54039230L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "JOHNSON RS FILTER SOFT/25",
                            Ref = 1576,
                            Size = "M"
                        },
                        new
                        {
                            Id = 2L,
                            Color = "",
                            Eancode = 54029644L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.5,
                            Nielsen2 = 0.5,
                            Nielsen3 = 0.5,
                            Nielsen4 = 0.5,
                            Product = "KENT CORE WHITE/20",
                            Ref = 237531,
                            Size = "S"
                        },
                        new
                        {
                            Id = 3L,
                            Color = "",
                            Eancode = 54029101L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.5,
                            Nielsen2 = 0.5,
                            Nielsen3 = 0.5,
                            Nielsen4 = 0.5,
                            Product = "KENT SURROUND LONG/20",
                            Ref = 242071,
                            Size = "S"
                        },
                        new
                        {
                            Id = 4L,
                            Color = "",
                            Eancode = 54029170L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "KENT SURROUND BROWN/20",
                            Ref = 243809,
                            Size = "S"
                        },
                        new
                        {
                            Id = 5L,
                            Color = "red",
                            Eancode = 54003859L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "KENT SURROUND BROWN/23",
                            Ref = 374350,
                            Size = "M"
                        },
                        new
                        {
                            Id = 6L,
                            Color = "yellow",
                            Eancode = 54003873L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "KENT SURROUND BROWN/30",
                            Ref = 393308,
                            Size = "L"
                        },
                        new
                        {
                            Id = 7L,
                            Color = "green",
                            Eancode = 54003811L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 1.0,
                            Product = "KENT SURROUND BROWN/36",
                            Ref = 410942,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = 8L,
                            Color = "",
                            Eancode = 54039018L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 1.0,
                            Product = "LUCKY BLUE SOFT/25",
                            Ref = 1490,
                            Size = "M"
                        },
                        new
                        {
                            Id = 9L,
                            Color = "",
                            Eancode = 54039001L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "LUCKY RED SOFT/25",
                            Ref = 1493,
                            Size = "M"
                        },
                        new
                        {
                            Id = 10L,
                            Color = "",
                            Eancode = 54029057L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "LUCKY STRIKE AUTHENTIC RED/20",
                            Ref = 242098,
                            Size = "S"
                        },
                        new
                        {
                            Id = 11L,
                            Color = "red",
                            Eancode = 54029064L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "LUCKY STRIKE AUTHENTIC BLUE/20",
                            Ref = 243906,
                            Size = "S"
                        },
                        new
                        {
                            Id = 12L,
                            Color = "",
                            Eancode = 54029040L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "LUCKY STRIKE RED/20",
                            Ref = 242101,
                            Size = "S"
                        },
                        new
                        {
                            Id = 13L,
                            Color = "red",
                            Eancode = 54003651L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.5,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "LUCKY STRIKE RED M/25",
                            Ref = 335029,
                            Size = "M"
                        },
                        new
                        {
                            Id = 14L,
                            Color = "",
                            Eancode = 54029200L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "LUCKY STRIKE RED 30",
                            Ref = 393924,
                            Size = "XL"
                        },
                        new
                        {
                            Id = 15L,
                            Color = "green",
                            Eancode = 54120006L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 0.5,
                            Nielsen4 = 1.0,
                            Product = "LUCKY STRIKE RED 36",
                            Ref = 410969,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = 16L,
                            Color = "green",
                            Eancode = 54039261L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "PALL MALL BLUE S/20",
                            Ref = 242152,
                            Size = "S"
                        },
                        new
                        {
                            Id = 17L,
                            Color = "red",
                            Eancode = 54002760L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.5,
                            Nielsen2 = 0.5,
                            Nielsen3 = 0.5,
                            Nielsen4 = 0.0,
                            Product = "PALL MALL BLUE M/23",
                            Ref = 411124,
                            Size = "M"
                        },
                        new
                        {
                            Id = 18L,
                            Color = "yellow",
                            Eancode = 54004573L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "PALL MALL BLUE/33",
                            Ref = 411140,
                            Size = "XL"
                        },
                        new
                        {
                            Id = 19L,
                            Color = "red",
                            Eancode = 40318257L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 0.0,
                            Product = "PALL MALL FLOW/20 ",
                            Ref = 243914,
                            Size = "S"
                        },
                        new
                        {
                            Id = 20L,
                            Color = "",
                            Eancode = 54029880L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "PALL MALL RED/20",
                            Ref = 242144,
                            Size = "S"
                        },
                        new
                        {
                            Id = 21L,
                            Color = "red",
                            Eancode = 54002777L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.5,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.5,
                            Nielsen4 = 0.5,
                            Product = "PALL MALL RED M/23",
                            Ref = 411175,
                            Size = "M"
                        },
                        new
                        {
                            Id = 22L,
                            Color = "",
                            Eancode = 54003958L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.5,
                            Nielsen2 = 1.0,
                            Nielsen3 = 0.5,
                            Nielsen4 = 1.0,
                            Product = "PALL MALL RED/33",
                            Ref = 411159,
                            Size = "XL"
                        },
                        new
                        {
                            Id = 23L,
                            Color = "",
                            Eancode = 54002746L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "PALL MALL RED/37",
                            Ref = 411167,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = 24L,
                            Color = "",
                            Eancode = 54004580L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "PALL MALL RED/47",
                            Ref = 411183,
                            Size = "XXXL"
                        },
                        new
                        {
                            Id = 25L,
                            Color = "",
                            Eancode = 54002692L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.5,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.5,
                            Nielsen4 = 0.0,
                            Product = "P.STUYVESANT RED KS/22",
                            Ref = 406848,
                            Size = "M"
                        },
                        new
                        {
                            Id = 26L,
                            Color = "green",
                            Eancode = 59026495L,
                            Fabrikant = "BAT",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "VOGUE BLUE SUPERSLIMS/20",
                            Ref = 124478,
                            Size = "S"
                        });
                });

            modelBuilder.Entity("Conway.Core.Model.BAT_Tabac", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Eancode")
                        .HasColumnType("bigint");

                    b.Property<string>("Fabrikant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Nielsen1")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen2")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen3")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen4")
                        .HasColumnType("float");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ref")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BAT_Tabacs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "",
                            Eancode = 54039285L,
                            Fabrikant = "BAT",
                            Groupe = "Tabac",
                            Nielsen1 = 0.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "AJJA 17 BLOND ROUGE/50G",
                            Ref = 2506,
                            Size = ""
                        },
                        new
                        {
                            Id = 2L,
                            Color = "",
                            Eancode = 54039292L,
                            Fabrikant = "BAT",
                            Groupe = "Tabac",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "AJJA 17 CORSE BLEU/50G",
                            Ref = 2503,
                            Size = ""
                        },
                        new
                        {
                            Id = 3L,
                            Color = "",
                            Eancode = 54039360L,
                            Fabrikant = "BAT",
                            Groupe = "Tabac",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "LUCKY STRIKE 100%US BL RED/30G",
                            Ref = 233773,
                            Size = ""
                        },
                        new
                        {
                            Id = 4L,
                            Color = "",
                            Eancode = 54039384L,
                            Fabrikant = "BAT",
                            Groupe = "Tabac",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "LUCKY STRIKE BLUE/50G",
                            Ref = 2486,
                            Size = ""
                        },
                        new
                        {
                            Id = 5L,
                            Color = "",
                            Eancode = 54039377L,
                            Fabrikant = "BAT",
                            Groupe = "Tabac",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "LUCKY STRIKE RED/50G",
                            Ref = 2483,
                            Size = ""
                        },
                        new
                        {
                            Id = 6L,
                            Color = "",
                            Eancode = 54039490L,
                            Fabrikant = "BAT",
                            Groupe = "Tabac",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "PALL MALL ROLL RED/30G",
                            Ref = 218731,
                            Size = ""
                        });
                });

            modelBuilder.Entity("Conway.Core.Model.ITB_Cigarette", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Eancode")
                        .HasColumnType("bigint");

                    b.Property<string>("Fabrikant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Nielsen1")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen2")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen3")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen4")
                        .HasColumnType("float");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ref")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ITB_Cigarettes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "",
                            Eancode = 54030022L,
                            Fabrikant = "ITB",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 0.0,
                            Product = "BASTOS ROUGE FILTER/25",
                            Ref = 1473,
                            Size = ""
                        },
                        new
                        {
                            Id = 2L,
                            Color = "",
                            Eancode = 4030600123331L,
                            Fabrikant = "ITB",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "GAULOISES BLONDES BLUE/20",
                            Ref = 252689,
                            Size = ""
                        },
                        new
                        {
                            Id = 3L,
                            Color = "yellow",
                            Eancode = 4030600236277L,
                            Fabrikant = "ITB",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "GAULOISES BLONDES BLUE L/25",
                            Ref = 375756,
                            Size = ""
                        },
                        new
                        {
                            Id = 4L,
                            Color = "yellow",
                            Eancode = 4030600274262L,
                            Fabrikant = "ITB",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "GAULOISES BLONDES BLUE XL/29",
                            Ref = 408263,
                            Size = ""
                        },
                        new
                        {
                            Id = 5L,
                            Color = "",
                            Eancode = 30002388L,
                            Fabrikant = "ITB",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 1.0,
                            Product = "GAULOISES BRUN BLEU FILTRE/20",
                            Ref = 1440,
                            Size = ""
                        },
                        new
                        {
                            Id = 6L,
                            Color = "",
                            Eancode = 4030600123423L,
                            Fabrikant = "ITB",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "JPS BLUE STREAM/20",
                            Ref = 252719,
                            Size = ""
                        },
                        new
                        {
                            Id = 7L,
                            Color = "",
                            Eancode = 4030600123393L,
                            Fabrikant = "ITB",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "JPS RED KS/20",
                            Ref = 252700,
                            Size = ""
                        },
                        new
                        {
                            Id = 8L,
                            Color = "yellow",
                            Eancode = 4030600236390L,
                            Fabrikant = "ITB",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "JPS RED/25",
                            Ref = 375799,
                            Size = ""
                        },
                        new
                        {
                            Id = 9L,
                            Color = "yellow",
                            Eancode = 4030600274323L,
                            Fabrikant = "ITB",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "JPS RED/30",
                            Ref = 408328,
                            Size = ""
                        },
                        new
                        {
                            Id = 10L,
                            Color = "yellow",
                            Eancode = 4030600274200L,
                            Fabrikant = "ITB",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "JPS RED/40",
                            Ref = 408336,
                            Size = ""
                        });
                });

            modelBuilder.Entity("Conway.Core.Model.ITB_Tabac", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Eancode")
                        .HasColumnType("bigint");

                    b.Property<string>("Fabrikant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Nielsen1")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen2")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen3")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen4")
                        .HasColumnType("float");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ref")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ITB_Tabacs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "",
                            Eancode = 8710900061002L,
                            Fabrikant = "ITB",
                            Groupe = "Tabac",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "DRUM ORIGINAL/50G",
                            Ref = 2600,
                            Size = ""
                        },
                        new
                        {
                            Id = 2L,
                            Color = "",
                            Eancode = 5411808067860L,
                            Fabrikant = "ITB",
                            Groupe = "Tabac",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "GAULOISES CAPORAL/50G (ZWAAR)",
                            Ref = 2457,
                            Size = ""
                        });
                });

            modelBuilder.Entity("Conway.Core.Model.JTI_Cigarette", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Eancode")
                        .HasColumnType("bigint");

                    b.Property<string>("Fabrikant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Nielsen1")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen2")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen3")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen4")
                        .HasColumnType("float");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ref")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JTI_Cigarettes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "",
                            Eancode = 54043206L,
                            Fabrikant = "JTI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 0.0,
                            Product = "CAMEL BLUE S/20",
                            Ref = 238295,
                            Size = "S"
                        },
                        new
                        {
                            Id = 2L,
                            Color = "red",
                            Eancode = 5410446006767L,
                            Fabrikant = "JTI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "CAMEL BLUE BOX/26",
                            Ref = 176605,
                            Size = "M"
                        },
                        new
                        {
                            Id = 3L,
                            Color = "green",
                            Eancode = 5410446012355L,
                            Fabrikant = "JTI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "CAMEL BLUE XXL/35",
                            Ref = 294519,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = 4L,
                            Color = "",
                            Eancode = 54043213L,
                            Fabrikant = "JTI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "CAMEL YELLOW S/20",
                            Ref = 238279,
                            Size = "S"
                        },
                        new
                        {
                            Id = 5L,
                            Color = "",
                            Eancode = 5410446006736L,
                            Fabrikant = "JTI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "CAMEL YELLOW L/26",
                            Ref = 176591,
                            Size = "L"
                        },
                        new
                        {
                            Id = 6L,
                            Color = "",
                            Eancode = 54043114L,
                            Fabrikant = "JTI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "CAMEL YELLOW XXL/35",
                            Ref = 267163,
                            Size = "XXL"
                        },
                        new
                        {
                            Id = 7L,
                            Color = "red",
                            Eancode = 5410446008938L,
                            Fabrikant = "JTI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 1.0,
                            Product = "CAMEL ESSENTIAL BROWN/20",
                            Ref = 238252,
                            Size = "X"
                        },
                        new
                        {
                            Id = 8L,
                            Color = "green",
                            Eancode = 54043237L,
                            Fabrikant = "JTI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "WINSTON BLUE/20",
                            Ref = 238333,
                            Size = "S"
                        },
                        new
                        {
                            Id = 9L,
                            Color = "",
                            Eancode = 54043138L,
                            Fabrikant = "JTI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "WINSTON CLASSIC/20 ",
                            Ref = 238325,
                            Size = "S"
                        },
                        new
                        {
                            Id = 10L,
                            Color = "",
                            Eancode = 54043121L,
                            Fabrikant = "JTI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "WINSTON CLASSIC GIGA/35",
                            Ref = 267198,
                            Size = "XXL"
                        });
                });

            modelBuilder.Entity("Conway.Core.Model.JTI_Tabac", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Eancode")
                        .HasColumnType("bigint");

                    b.Property<string>("Fabrikant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Nielsen1")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen2")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen3")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen4")
                        .HasColumnType("float");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ref")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JTI_Tabacs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "",
                            Eancode = 5410446008259L,
                            Fabrikant = "JTI",
                            Groupe = "Tabac",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "WINSTON RYO BLOND/30G",
                            Ref = 238384,
                            Size = ""
                        },
                        new
                        {
                            Id = 2L,
                            Color = "",
                            Eancode = 5411808067860L,
                            Fabrikant = "JTI",
                            Groupe = "Tabac",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "WINSTON RYO ORIGINAL/40G",
                            Ref = 2622,
                            Size = ""
                        });
                });

            modelBuilder.Entity("Conway.Core.Model.PMI_Cigarette", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Eancode")
                        .HasColumnType("bigint");

                    b.Property<string>("Fabrikant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Nielsen1")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen2")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen3")
                        .HasColumnType("float");

                    b.Property<double>("Nielsen4")
                        .HasColumnType("float");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ref")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PMI_Cigarettes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "",
                            Eancode = 54140660L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "CHESTERFIELD RED/20",
                            Ref = 250546,
                            Size = ""
                        },
                        new
                        {
                            Id = 2L,
                            Color = "red",
                            Eancode = 54141681L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "CHESTERFIELD RED/23",
                            Ref = 370339,
                            Size = ""
                        },
                        new
                        {
                            Id = 3L,
                            Color = "red",
                            Eancode = 54002401L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "CHESTERFIELD RED/34",
                            Ref = 370363,
                            Size = ""
                        },
                        new
                        {
                            Id = 4L,
                            Color = "green",
                            Eancode = 54014534L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "CHESTERFIELD RED XL/31",
                            Ref = 408794,
                            Size = ""
                        },
                        new
                        {
                            Id = 5L,
                            Color = "green",
                            Eancode = 54014510L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "CHESTERFIELD RED BIG/47",
                            Ref = 408786,
                            Size = ""
                        },
                        new
                        {
                            Id = 6L,
                            Color = "",
                            Eancode = 54140424L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "L&M BLUE/20",
                            Ref = 246514,
                            Size = ""
                        },
                        new
                        {
                            Id = 7L,
                            Color = "red",
                            Eancode = 54002364L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "L&M BLUE M/23",
                            Ref = 367567,
                            Size = ""
                        },
                        new
                        {
                            Id = 8L,
                            Color = "red",
                            Eancode = 54002388L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "L&M BLUE/27",
                            Ref = 367540,
                            Size = ""
                        },
                        new
                        {
                            Id = 9L,
                            Color = "green",
                            Eancode = 54002418L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "L&M BLUE/32",
                            Ref = 371874,
                            Size = ""
                        },
                        new
                        {
                            Id = 10L,
                            Color = "",
                            Eancode = 54140431L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "L&M ORIGINAL/20",
                            Ref = 246506,
                            Size = ""
                        },
                        new
                        {
                            Id = 11L,
                            Color = "yellow",
                            Eancode = 54014688L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "L&M ORIGINAL M/23",
                            Ref = 408808,
                            Size = ""
                        },
                        new
                        {
                            Id = 12L,
                            Color = "yellow",
                            Eancode = 54014541L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "L&M ORIGINAL L/27",
                            Ref = 408824,
                            Size = ""
                        },
                        new
                        {
                            Id = 13L,
                            Color = "yellow",
                            Eancode = 54014459L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "L&M ORIGINAL XL/31",
                            Ref = 382744,
                            Size = ""
                        },
                        new
                        {
                            Id = 14L,
                            Color = "",
                            Eancode = 54141643L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "L&m Orignal XXL/39",
                            Ref = 371920,
                            Size = ""
                        },
                        new
                        {
                            Id = 15L,
                            Color = "green",
                            Eancode = 54014657L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "L&M ORIGINAL BIG/48",
                            Ref = 406791,
                            Size = ""
                        },
                        new
                        {
                            Id = 16L,
                            Color = "red",
                            Eancode = 54002395L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "L&M SILVER/23",
                            Ref = 367575,
                            Size = ""
                        },
                        new
                        {
                            Id = 17L,
                            Color = "",
                            Eancode = 54140875L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "MARLBORO FINE TOUCH/20",
                            Ref = 247464,
                            Size = ""
                        },
                        new
                        {
                            Id = 18L,
                            Color = "",
                            Eancode = 54140851L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "MARLBORO GOLD/20",
                            Ref = 247456,
                            Size = ""
                        },
                        new
                        {
                            Id = 19L,
                            Color = "red",
                            Eancode = 54141520L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "MARLBORO GOLD/23",
                            Ref = 371947,
                            Size = ""
                        },
                        new
                        {
                            Id = 20L,
                            Color = "green",
                            Eancode = 54014633L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "MARLBORO GOLD L 27",
                            Ref = 407690,
                            Size = ""
                        },
                        new
                        {
                            Id = 21L,
                            Color = "red",
                            Eancode = 54141452L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "MARLBORO GOLD/30",
                            Ref = 371939,
                            Size = ""
                        },
                        new
                        {
                            Id = 22L,
                            Color = "green",
                            Eancode = 54002326L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "MARLBORO GOLD XXL/37",
                            Ref = 416762,
                            Size = ""
                        },
                        new
                        {
                            Id = 23L,
                            Color = "red",
                            Eancode = 54014404L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "Marlboro bright/20",
                            Ref = 384151,
                            Size = ""
                        },
                        new
                        {
                            Id = 24L,
                            Color = "red",
                            Eancode = 54141421L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "MARLBORO PRIME/20",
                            Ref = 246468,
                            Size = ""
                        },
                        new
                        {
                            Id = 25L,
                            Color = "red",
                            Eancode = 54140806L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 0.0,
                            Nielsen2 = 0.0,
                            Nielsen3 = 0.0,
                            Nielsen4 = 0.0,
                            Product = "MARLBORO RED 100/20",
                            Ref = 250511,
                            Size = ""
                        },
                        new
                        {
                            Id = 26L,
                            Color = "",
                            Eancode = 54140813L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "MARLBORO RED/20",
                            Ref = 251895,
                            Size = ""
                        },
                        new
                        {
                            Id = 27L,
                            Color = "",
                            Eancode = 54002487L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "MARLBORO RED/23",
                            Ref = 370347,
                            Size = ""
                        },
                        new
                        {
                            Id = 28L,
                            Color = "",
                            Eancode = 54002142L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "MARLBORO RED/27",
                            Ref = 333441,
                            Size = ""
                        },
                        new
                        {
                            Id = 29L,
                            Color = "green",
                            Eancode = 54141506L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "MARLBORO RED/37",
                            Ref = 371807,
                            Size = ""
                        },
                        new
                        {
                            Id = 30L,
                            Color = "green",
                            Eancode = 54014503L,
                            Fabrikant = "PMI",
                            Groupe = "Cigarette",
                            Nielsen1 = 1.0,
                            Nielsen2 = 1.0,
                            Nielsen3 = 1.0,
                            Nielsen4 = 1.0,
                            Product = "MARLBORO RED BIG 48",
                            Ref = 416789,
                            Size = ""
                        });
                });

            modelBuilder.Entity("Conway.Core.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Breedte")
                        .HasColumnType("float");

                    b.Property<double>("Diepte")
                        .HasColumnType("float");

                    b.Property<long>("Eancode")
                        .HasColumnType("bigint");

                    b.Property<string>("Fabrikant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Hoogte")
                        .HasColumnType("float");

                    b.Property<int>("Inhoud")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prijs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
